### ISSUE TITLE
alter table test_update delete node report error:  this operation is not permitted

### ISSUE THREAD

**Issue by l1t1** [Tencent/TBase#63]
create table test_update( id int,code int,primary key(id));
insert into test_update select id * 100+code%100 ,id*100+code%100 from generate_series(1,704754) id,generate_series(1,17) code;

test=# alter table test_update delete node(dn001);
ERROR:  this operation is not permitted

**Comment by l1t1** [comment]
but in postgres xl, it works
test=# alter table test_update delete node(dn1);
ALTER TABLE
Time: 38552.665 ms (00:38.553)

**Comment by JennyJennyChen** [comment]
In order to facilitate expansion, TBase modified PGXL and added a shard map layer. If you want to delete a node, you must move all shards on this node to other nodes and modify the shard routing information. This part is done through the management and control system, which is not open source for the time being
